# Generated by Django 4.2.14 on 2024-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_todo_name_todo_email_todo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='todo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
