# Generated by Django 4.2.14 on 2024-07-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_complete_todo_description_todo_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='password',
        ),
    ]
